version: "3.7"

services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
  server:
    extends:
      service: builder
    command: [
      "go", "run", "main.go"
      ]
    environment:
        HTTP_ADDR: 0.0.0.0:8100
    ports:
        - 8100:8100